#ifndef SENSORS_H_
#define SENSORS_H_

#include "sample_batch.pb.h"

#define MEASUREMENT_INTERVAL_MS 1000

/* PRESSURE SENSOR */
#define PRESSURE_SENSOR_CHANNEL ADC_CHANNEL_4 // GPIO32 (ADC1)
#define PRESSURE_SENSOR_ADC_WIDTH ADC_BITWIDTH_12
#define PRESSURE_SENSOR_ADC_ATTENUATION ADC_ATTEN_DB_12

#define PRESSURE_SENSOR_VOLTAGE_MAX 3.3
#define PRESSURE_MIN_VALUE 0.0440

/* FLOW SENSOR */
#define FLOW_SENSOR_PIN GPIO_NUM_25
#define FLOW_SENSOR_PULSES_PER_LITER 6.6
#define MAX_FLOW_LPM 30

void app_sensors_init(void);
void app_sensors_read(Sample*);

#endif